# CMAKE generated file: DO NOT EDIT!
# Generated by "NMake Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE
NULL=nul
!ENDIF
SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\TheNosiriN\Documents\CppProjects\universe

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\TheNosiriN\Documents\CppProjects\universe

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	echo >nul && "C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache\fast: edit_cache
.PHONY : edit_cache\fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	echo >nul && "C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache\fast: rebuild_cache
.PHONY : rebuild_cache\fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\TheNosiriN\Documents\CppProjects\universe\CMakeFiles C:\Users\TheNosiriN\Documents\CppProjects\universe\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\TheNosiriN\Documents\CppProjects\universe\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) clean
.PHONY : clean

# The main clean target
clean\fast: clean
.PHONY : clean\fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall\fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named app

# Build rule for target.
app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) app
.PHONY : app

# fast build rule for target.
app\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\app.dir\build
.PHONY : app\fast

#=============================================================================
# Target rules for targets named Shaders

# Build rule for target.
Shaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) Shaders
.PHONY : Shaders

# fast build rule for target.
Shaders\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Shaders.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Shaders.dir\build
.PHONY : Shaders\fast

src\Application.obj: src\Application.cpp.obj
.PHONY : src\Application.obj

# target to build an object file
src\Application.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\app.dir\src\Application.cpp.obj
.PHONY : src\Application.cpp.obj

src\Application.i: src\Application.cpp.i
.PHONY : src\Application.i

# target to preprocess a source file
src\Application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\app.dir\src\Application.cpp.i
.PHONY : src\Application.cpp.i

src\Application.s: src\Application.cpp.s
.PHONY : src\Application.s

# target to generate assembly for a file
src\Application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\app.dir\src\Application.cpp.s
.PHONY : src\Application.cpp.s

src\Camera.obj: src\Camera.cpp.obj
.PHONY : src\Camera.obj

# target to build an object file
src\Camera.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\app.dir\src\Camera.cpp.obj
.PHONY : src\Camera.cpp.obj

src\Camera.i: src\Camera.cpp.i
.PHONY : src\Camera.i

# target to preprocess a source file
src\Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\app.dir\src\Camera.cpp.i
.PHONY : src\Camera.cpp.i

src\Camera.s: src\Camera.cpp.s
.PHONY : src\Camera.s

# target to generate assembly for a file
src\Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\app.dir\src\Camera.cpp.s
.PHONY : src\Camera.cpp.s

src\Universe.obj: src\Universe.cpp.obj
.PHONY : src\Universe.obj

# target to build an object file
src\Universe.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\app.dir\src\Universe.cpp.obj
.PHONY : src\Universe.cpp.obj

src\Universe.i: src\Universe.cpp.i
.PHONY : src\Universe.i

# target to preprocess a source file
src\Universe.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\app.dir\src\Universe.cpp.i
.PHONY : src\Universe.cpp.i

src\Universe.s: src\Universe.cpp.s
.PHONY : src\Universe.s

# target to generate assembly for a file
src\Universe.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\app.dir\src\Universe.cpp.s
.PHONY : src\Universe.cpp.s

src\main.obj: src\main.cpp.obj
.PHONY : src\main.obj

# target to build an object file
src\main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\app.dir\src\main.cpp.obj
.PHONY : src\main.cpp.obj

src\main.i: src\main.cpp.i
.PHONY : src\main.i

# target to preprocess a source file
src\main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\app.dir\src\main.cpp.i
.PHONY : src\main.cpp.i

src\main.s: src\main.cpp.s
.PHONY : src\main.s

# target to generate assembly for a file
src\main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\app.dir\src\main.cpp.s
.PHONY : src\main.cpp.s

src\renderers.obj: src\renderers.cpp.obj
.PHONY : src\renderers.obj

# target to build an object file
src\renderers.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\app.dir\src\renderers.cpp.obj
.PHONY : src\renderers.cpp.obj

src\renderers.i: src\renderers.cpp.i
.PHONY : src\renderers.i

# target to preprocess a source file
src\renderers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\app.dir\src\renderers.cpp.i
.PHONY : src\renderers.cpp.i

src\renderers.s: src\renderers.cpp.s
.PHONY : src\renderers.s

# target to generate assembly for a file
src\renderers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\app.dir\src\renderers.cpp.s
.PHONY : src\renderers.cpp.s

src\ui.obj: src\ui.cpp.obj
.PHONY : src\ui.obj

# target to build an object file
src\ui.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\app.dir\src\ui.cpp.obj
.PHONY : src\ui.cpp.obj

src\ui.i: src\ui.cpp.i
.PHONY : src\ui.i

# target to preprocess a source file
src\ui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\app.dir\src\ui.cpp.i
.PHONY : src\ui.cpp.i

src\ui.s: src\ui.cpp.s
.PHONY : src\ui.s

# target to generate assembly for a file
src\ui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\app.dir\src\ui.cpp.s
.PHONY : src\ui.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... Shaders
	@echo ... app
	@echo ... src/Application.obj
	@echo ... src/Application.i
	@echo ... src/Application.s
	@echo ... src/Camera.obj
	@echo ... src/Camera.i
	@echo ... src/Camera.s
	@echo ... src/Universe.obj
	@echo ... src/Universe.i
	@echo ... src/Universe.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/renderers.obj
	@echo ... src/renderers.i
	@echo ... src/renderers.s
	@echo ... src/ui.obj
	@echo ... src/ui.i
	@echo ... src/ui.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

